language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.8"
matrix:
  allow_failures:
    - perl: "5.19"
notifications:
  recipients:
    - libsys@qut.edu.au
  email:
    on_success: change
    on_failure: always

